# Generated by Django 4.1.2 on 2022-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoName', models.CharField(max_length=300)),
                ('promoCode', models.CharField(max_length=300)),
                ('expireDate', models.CharField(max_length=300)),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
