# Generated by Django 4.1.2 on 2022-11-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
