# Generated by Django 4.1.2 on 2022-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phonenumber',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
