# Generated by Django 4.1.2 on 2022-11-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cardnum',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cvv',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='expiration_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='zip_code',
            field=models.CharField(blank=True, default='30605', max_length=5),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
