# Generated by Django 4.1.2 on 2022-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_cardnum_useraccount_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='promotion_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
