# Generated by Django 4.1.2 on 2022-12-05 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_total_price_alter_booking_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
