# Generated by Django 4.1.2 on 2022-12-03 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.CharField(blank=True, default='', max_length=16)),
                ('cvv', models.CharField(blank=True, default='', max_length=3)),
                ('expiration_year', models.CharField(blank=True, default='', max_length=4)),
                ('zip_code', models.CharField(blank=True, default='30605', max_length=5)),
                ('UserAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
