# Generated by Django 4.1.2 on 2022-12-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeGroup', models.CharField(max_length=30)),
                ('Seat_no', models.IntegerField()),
                ('Ticket_holder_name', models.CharField(max_length=100)),
                ('Booking_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
