# Generated by Django 4.1.2 on 2022-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_seats', models.IntegerField()),
                ('showRoom_name', models.CharField(max_length=200, unique=True)),
                ('seat_info', models.JSONField()),
            ],
        ),
    ]
