# Generated by Django 4.1.2 on 2022-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='seat_info',
            field=models.CharField(max_length=100),
        ),
    ]
