# Generated by Django 4.1.2 on 2022-11-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_showroom_seat_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='remaining_seats',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='seat_info',
        ),
    ]
