# Generated by Django 4.1.2 on 2022-11-29 05:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0002_rename_show_date_show_start_date_show_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField(default=datetime.date(2022, 11, 29))),
                ('booked_seats', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.show')),
            ],
        ),
    ]
