# Generated by Django 4.1.2 on 2022-12-08 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked_seats_tracker', '0005_alter_bookedseats_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseats',
            name='show_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 12, 8, 14, 48, 0, 465169)),
        ),
    ]
