# Generated by Django 4.1.2 on 2022-12-08 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked_seats_tracker', '0006_alter_bookedseats_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseats',
            name='show_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 12, 8, 14, 55, 50, 522186)),
        ),
    ]
