# Generated by Django 4.1.2 on 2023-01-24 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked_seats_tracker', '0007_alter_bookedseats_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseats',
            name='show_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 1, 24, 15, 50, 1, 307788)),
        ),
    ]
