# Generated by Django 4.1.2 on 2022-11-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_reviews_alter_movie_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_cast',
            field=models.CharField(max_length=3000),
        ),
    ]
