# Generated by Django 4.1.2 on 2022-11-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(max_length=3000),
        ),
    ]
