# Generated by Django 4.1.2 on 2022-11-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_info', models.CharField(max_length=300)),
                ('promo_code', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default='false')),
                ('percentage', models.FloatField()),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
