# Generated by Django 4.1.2 on 2022-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotions',
            old_name='expiration_date',
            new_name='promotion_expiration',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='promotion_info',
            new_name='promotion_name',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='percentage',
            new_name='promotion_percentage',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotion_code',
            field=models.CharField(default='abc', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
